services:
  - type: web
    name: automerge-ai-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: automerge-ai-db
          property: connectionString
      - key: GITHUB_CLIENT_ID
        sync: false
      - key: GITHUB_CLIENT_SECRET
        sync: false
      - key: GITHUB_REDIRECT_URI
        sync: false
      - key: GITHUB_WEBHOOK_SECRET
        sync: false

databases:
  - name: automerge-ai-db
    databaseName: automerge_ai
    user: automerge_ai_user