"""Initial migration

Revision ID: 8fbadbf9f751
Revises: 
Create Date: 2025-03-17 22:51:37.953196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fbadbf9f751'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('issues', sa.Column('state', sa.String(), nullable=True))
    op.add_column('issues', sa.Column('html_url', sa.String(), nullable=True))
    op.add_column('issues', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('issues', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('issues', sa.Column('is_ai_fixable', sa.Boolean(), nullable=True))
    op.add_column('issues', sa.Column('labels', sa.String(), nullable=True))
    op.drop_constraint('users_github_access_token_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_github_access_token_key', 'users', ['github_access_token'])
    op.drop_column('issues', 'labels')
    op.drop_column('issues', 'is_ai_fixable')
    op.drop_column('issues', 'updated_at')
    op.drop_column('issues', 'created_at')
    op.drop_column('issues', 'html_url')
    op.drop_column('issues', 'state')
    op.drop_column('issues', 'description')
    # ### end Alembic commands ###
